### PR TITLE
Update submodule to latest `master` in `microsoft/main`

### PR DESCRIPTION
**Pull request by ghost**
Hi! I'm a bot, and this is an automatically generated upstream sync PR. 🔃

After submitting the PR, I will attempt to enable auto-merge in the "merge commit" configuration.

For more information, visit [sync documentation in microsoft/go-infra](https://github.com/microsoft/go-infra/tree/main/docs/automation/sync.md).

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Thanks! Auto-approving.

**Comment by dagood** [comment]
FYI @qmuntal @jaredpar, patch conflicts in the crypto backend area. (Haven't investigated beyond noticing the filenames.)

**Comment by dagood** [comment]
After fixing the patch-time break, there's still a build-time break. It's because NewGCMTLS was changed:
```diff
- func (c *aesCipher) NewGCMTLS() (cipher.AEAD, error) {
+ func NewGCMTLS(c cipher.Block) (cipher.AEAD, error) {
```

https://github.com/golang/go/commit/ea5d7cbc2644643331bd675b1ebdf0aaac7419f1#diff-ed9ac51b1aba311ba2934af20134e4b05860eec9b6fba6209c8e675b9eb88096

Change was based on this feedback: https://go-review.googlesource.com/c/go/+/403154/2/src/crypto/tls/cipher_suites.go#529

I think an approach that probably makes sense is:

1. Implement both forms of the func in go-crypto-openssl.
2. Add the mapping to the new func in the Go patch, for 1.19+.
3. Wait until 1.18 is no longer supported.
4. Remove the old form of the func from go-crypto-openssl.

I'm trying a Go-only approach in this draft PR, although we probably shouldn't go with it, to avoid maintaining crypto logic in our patch files:
* https://github.com/microsoft/go/pull/597

**Comment by qmuntal** [comment]
Good job tracking down the conflicts @dagood.

I've implemented your first proposed solution in https://github.com/microsoft/go-crypto-openssl/pull/30, which will result in a cleaner patch file.

**Comment by dagood** [comment]
Closing: update and fixes implemented by https://github.com/microsoft/go/pull/597.

**Pull request closed without merging**
