### PR TITLE
Update submodule to latest `master` in `microsoft/main`

### PR DESCRIPTION
**Pull request by ghost**
Hi! I'm a bot, and this is an automatically generated upstream sync PR. 🔃

After submitting the PR, I will attempt to enable auto-merge in the "merge commit" configuration.

For more information, visit [sync documentation in microsoft/go-infra](https://github.com/microsoft/go-infra/tree/main/docs/automation/sync.md).

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Thanks! Auto-approving.

**Comment by qmuntal** [comment]
Please don't resolve this conflicts until all my SymCrypt PRs are merged.

**Review by dagood — DISMISSED** [review]
^

**Comment by qmuntal** [comment]
CI is failing due to https://github.com/golang/go/issues/70463. I've already sent a fix for it: https://go-review.googlesource.com/c/go/+/630096.

**Review by karianna — DISMISSED** [review]

**Comment by qmuntal** [comment]
Patch conflicts resolved, now I only have to fix the tests...

**Comment by qmuntal** [comment]
For https://github.com/microsoft/go/issues/1416.

**Comment by qmuntal** [comment]
The fixes necessary to reconcile our fork with upstream are growing to the point that the PR is hard to review. I'll be extracting some of the commits to their own PR.

**Comment by qmuntal** [comment]
Finally, no conflicts and tests passing 🎉.

**Review by gdams — APPROVED** [review]
Let's merge it!

**Pull request merged**
