### PR TITLE
Update submodule to latest `master` in `microsoft/main`

### PR DESCRIPTION
**Pull request by ghost**
Hi! I'm a bot, and this is an automatically generated upstream sync PR. 🔃

After submitting the PR, I will attempt to enable auto-merge in the "merge commit" configuration.

For more information, visit [sync documentation in microsoft/go-infra](https://github.com/microsoft/go-infra/tree/main/docs/automation/sync.md).

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Thanks! Auto-approving.

**Comment by karianna** [comment]
Hmm, it seems this bot always auto approves even before CI has a chance to check things, should we change that behaviour?

**Comment by dagood** [comment]
> Hmm, it seems this bot always auto approves even before CI has a chance to check things, should we change that behaviour?

Do you have some ideas why we might want to change it, or concerns?

**Comment by gdams** [comment]
> > Hmm, it seems this bot always auto approves even before CI has a chance to check things, should we change that behaviour?
> 
> Do you have some ideas why we might want to change it, or concerns?

I guess it might not be a bad idea to have it only approve it if all CI is green? It doesn't bother me that much though

**Comment by dagood** [comment]
> I guess it might not be a bad idea to have it only approve it if all CI is green?

I don't think this behavior would be bad, but I also don't see any reason it would be better. I don't expect human reviewers to wait for CI to finish either.

**Review by mertakman — APPROVED** [review]

**Comment by dagood** [comment]
CI failure is an upstream change: filed https://github.com/golang/go/issues/68121.

**Comment by karianna** [comment]
> > I guess it might not be a bad idea to have it only approve it if all CI is green?
> 
> I don't think this behavior would be bad, but I also don't see any reason it would be better. I don't expect human reviewers to wait for CI to finish either.

I'll ask a different Q - what is the bot checking for before it gives the approval?

**Comment by dagood** [comment]
> what is the bot checking for before it gives the approval?

It doesn't check anything. For context, microsoft-golang-review-bot and microsoft-golang-bot are separate accounts, but they are not independent in any way. A pipeline creates the PR with one account's PAT and (during the same command) uses the other account's PAT to approve it and turn on auto-merge. GitHub makes sure the CI passes before automerge goes ahead, because the branch is protected.

We have branch protection requiring a review approval--the goal is making dev PRs comfortable. The microsoft-golang-review-bot approvals are just a way to make auto-sync work without removing/bypassing branch protection.

**Comment by karianna** [comment]
> > what is the bot checking for before it gives the approval?
> 
> It doesn't check anything. For context, microsoft-golang-review-bot and microsoft-golang-bot are separate accounts, but they are not independent in any way. A pipeline creates the PR with one account's PAT and (during the same command) uses the other account's PAT to approve it and turn on auto-merge. GitHub makes sure the CI passes before automerge goes ahead, because the branch is protected.
> 
> We have branch protection requiring a review approval--the goal is making dev PRs comfortable. The microsoft-golang-review-bot approvals are just a way to make auto-sync work without removing/bypassing branch protection.

Cool, thanks for the context!

**Pull request merged**
