### PR TITLE
Upgrade go-crypto-openssl to v0.2.4

### PR DESCRIPTION
**Pull request by qmuntal**
Release notes: https://github.com/microsoft/go-crypto-openssl/releases/tag/v0.2.4

### CODE REVIEW

**Review by dagood — APPROVED** [review]

**Comment by chsienki** [comment]
Are the test failures legitimate issues?

**Comment by dagood** [comment]
They seem to me to be, unfortunately. Can browse them at https://dev.azure.com/dnceng-public/public/_build/results?buildId=141404&view=ms.vss-test-web.build-test-results-tab. @qmuntal mentioned that there are failures in the sync, so I'm sure he'll be working on it. 😄

**Review by jaredpar — APPROVED** [review]

**Comment by qmuntal** [comment]
I've submitted a PR to fix them: https://github.com/microsoft/go-crypto-openssl/pull/46

**Comment by qmuntal** [comment]
Superseded by #855

**Pull request closed without merging**
