### PR TITLE
[release-branch.go1.21] Replace RtlGetNtVersionNumbers with RtlGetVersion

### PR DESCRIPTION
**Pull request by qmuntal**
This is a cherry-pick of [CL 571015](https://go-review.googlesource.com/c/go/+/571015) and [CL 531235](https://go-review.googlesource.com/c/go/+/531235), as upstream won't backport them to Go 1.21.

The cherry-pick are not completely clean, they needed some manual conflict resolution.

### CODE REVIEW

**Review by gdams — APPROVED** [review]

**Comment by gdams** [comment]
Actually I'm seeing this in the build logs:

```output
D:\a\_work\1\s\go\src\syscall\exec_windows.go:322:2: undefined: rtlGetNtVersionNumbers
```

**Comment by qmuntal** [comment]
> Actually I'm seeing this in the build logs:

Wops, I also need to backport [CL 531235](https://go-review.googlesource.com/c/go/+/531235) then. It is a CL I sent some time ago to remove some Windows 7 related-code which was using `RtlGetNtVersionNumbers`. It is safe to backport it because Windows 7 is not officially supported on Go 1.21 (see https://go.dev/wiki/Windows).

**Review by dagood — APPROVED** [review]

**Comment by dagood** [comment]
I just noticed going through my email that this was merged into `dev/auto-sync/microsoft/release-branch.go1.21` rather than the actual release branch, probably not intended. 😄

(Also https://github.com/microsoft/go/pull/1179)

**Comment by qmuntal** [comment]
> I just noticed going through my email that this was merged into `dev/auto-sync/microsoft/release-branch.go1.21` rather than the actual release branch, probably not intended. 😄
> 
> (Also #1179)

Wops, good catch. Fixed.

**Pull request merged**
