### PR TITLE
Update public pool names

### PR DESCRIPTION
**Pull request by alexperovich**
This change is required for builds to continue working in the new org, dev.azure.com/dnceng-public.

### CODE REVIEW

**Review by dagood — APPROVED** [review]

**Comment by alexperovich** [comment]
It looks like these pipelines have gotten into a weird state. I am checking things.

**Comment by dagood** [comment]
Forcing merge so we can at least have public CI trigger, even though it can't report back to GitHub yet. (Go ahead and submit a new PR to test out webhook stuff, and we can close it later.)

**Pull request merged**
