### PR TITLE
[microsoft/release-branch.go1.23] Update submodule for 1.23

### PR DESCRIPTION
**Pull request by dagood**

### CODE REVIEW

**Comment by gdams** [comment]
I see a test failure on windows

**Comment by dagood** [comment]
That's an interesting one... when testing with `GOEXPERIMENT=cngcrypto` in particular, telemetry isn't working (according to these test cases). Taking a look.

**Comment by dagood** [comment]
It repros upstream with `$env:GOEXPERIMENT='aliastypeparams'` (or anything else, it seems). Filing an issue.
(Edit: filed https://github.com/golang/go/issues/68579)

**Comment by dagood** [comment]
For now, I added a patch to let the test case pass anyway, although the patch is specific to our CI case (cngcrypto).

**Review by karianna — APPROVED** [review]

**Pull request merged**
