### PR TITLE
Update submodule to latest `master` in `microsoft/main`

### PR DESCRIPTION
**Pull request by ghost**
Hi! I'm a bot, and this is an automatically generated upstream sync PR. 🔃

After submitting the PR, I will attempt to enable auto-merge in the "merge commit" configuration.

For more information, visit [sync documentation in microsoft/go-infra](https://github.com/microsoft/go-infra/tree/main/docs/automation/sync.md).

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Thanks! Auto-approving.

**Review by karianna — CHANGES_REQUESTED** [review]
Needs manual intervention

**Comment by dagood** [comment]
> Needs manual intervention

@karianna It looks like there was some flakiness on https://github.com/microsoft/go/commit/79f091646ff365e5b649d4c1e20a003e73dfd583, but the current commit is green. (Perhaps something about the VM changed, a bad change merged upstream that was fixed (perhaps not intentionally), or both.) Or did you see something different that needs to be addressed?

**Review by karianna — APPROVED** [review]

**Comment by karianna** [comment]
> > Needs manual intervention
> 
> @karianna It looks like there was some flakiness on [79f0916](https://github.com/microsoft/go/commit/79f091646ff365e5b649d4c1e20a003e73dfd583), but the current commit is green. (Perhaps something about the VM changed, a bad change merged upstream that was fixed (perhaps not intentionally), or both.) Or did you see something different that needs to be addressed?

Just saw that flaikness.

**Pull request merged**
